### ISSUE TITLE
Adapt FlexibleDecays to #227

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#229]
This is related to #227 in conjunction with #164. We had a special case of fill function
```cpp
template <class Model>    
void fill(    
   const SM_slha& model,    
   const softsusy::QedQcd& qedqcd,    
   const SM_scales& scales,    
   const SM_observables& observables,    
   const SM_decays& decays)    
{    
   SM_slha_io slha_io;    
    
   slha_io.fill_spectrum_generator_data(model, qedqcd, scales, observables);    
   slha_io.fill_decays_data(decays);    
}
```
@Expander, since you've removed `fill_spectrum_generator_data` would you like to suggest a replacement? Should we have 2 version of `fill` at all?

**Comment by Expander** [comment]
I would suggest to extend the currently available `fill()` function like so:
~~~.cpp
template <class... Ts>
void @ModelName@_slha_io::fill(
   const std::tuple<Ts...>& models,
   const softsusy::QedQcd& qedqcd,
   const @ModelName@_scales& scales,
   const @ModelName@_observables& observables,
   const SM_decays* decays)
{
   const auto& model = std::get<0>(models);
   const auto& problems = model.get_problems();

   set_spinfo(problems);
   set_sminputs(qedqcd);
   set_input(model.get_input());
   if (!problems.have_problem()) {
      set_spectrum(models);
      set_extra(model, scales, observables);
      // this is new:
      if (decays) {
         fill_decays_data(*decays);
      }
   }
}
~~~
The `decays` pointer should have a default parameter value of `nullptr`. This has the advantage, that it is now an "optional" parameter, that can be omitted.

What do you think?

**Comment by wkotlarski** [comment]
Hopefully I've fixed the decays in the last commit. I've modified ` templates/run_cmd_line.cpp.in` and `templates/slha_io.hpp.in`. I've used `unique_ptr` and `move` if you're ok with that.

**Comment by Expander** [comment]
TBH, I'm not happy about passing a `unique_ptr` to the `fill()` function, because this restricts the usability of the function, because you're transferring ownership and cannot use the `decays` object afterwards. For example, the following use case does not seem to work now:
~~~.cpp
auto decays = calculate_decays(...);
slha_io.fill(..., &decays);
std::cout << decays << std::endl; // use decays after passing them to fill(...)
~~~
Why don't you simply pass a pointer to an object on the stack? As far as I can see, we don't need to pass ownership (or share lifetime), because the `fill()` routine does not store the decays. Or am I missing something?

**Comment by wkotlarski** [comment]
Thanks for the comment. You're of course right. The idea behind it was that we never use it after the `fill` call, so I thought it's a good idea. Can I at least use a `shared_ptr` instead of a raw one? I always forget to deallocate them :)

**Comment by pathron** [comment]
You and everyone else who uses them it seems...

**Comment by Expander** [comment]
Yes, that'd be much better.

Although, I still don't understand why we have to dynamically allocate a decays object at all. Which benefit does this have/which pattern are you following? For example, we're currently not allocating an object for the observables, and this seems to work just fine. :)

**Comment by wkotlarski** [comment]
With signature
```cpp
template <class... Ts>
void @ModelName@_slha_io::fill(
   const std::tuple<Ts...>& models,
   const softsusy::QedQcd& qedqcd,
   const @ModelName@_scales& scales,
   const @ModelName@_observables& observables,
   const SM_decays* decays)
```
I have to pass pointer to `decays`, don't I?

**Comment by pathron** [comment]
sorry stupid question.. but what do actually need to do with decays in the fill object?  It looks like you don't need to change anything in it anyway?  is that right?

**Comment by wkotlarski** [comment]
Because it states it's a "Convenience wrapper function to fill all information at once" :)

**Comment by pathron** [comment]
Sorry its fine, I deleted my question already, as it made no sense :).

**Comment by Expander** [comment]
Yes, my proposal was to use a raw pointer. :) I intended to pass an address to an object on the stack (not the heap), i.e.
~~~.cpp
auto decays = calculate_decays(...); // object on the stack
slha_io.fill(..., &decays); // pass pointer to stack object to fill slha_io
// can use decays here
~~~
This will work perfectly fine, as long as `slha_io` does not store the pointer (which it does not do and must not do.) From looking at your code, I don't see a reason why we should use a `shared_ptr` to a heap objeckt. (Maybe I'm overlooking something, though.)

I'd use a `shared_ptr` if we want to "share ownership", i.e. the caller *and* the `slha_io` object should *both own* the `decays` object, for example like this:
~~~.cpp
auto decays_ptr = make_shared<Decays>(...); // object on the heap
slha_io.fill(..., decay_ptr); // decays_ptr will be stored inside slha_io
// can use decay_ptr here
~~~
However, since the `slha_io` object does not take/need ownership of the `decays` object, I see no need to use a `shared_ptr` here. An ordinary pointer to a stack object will do the job (and is simpler and maybe even faster).

**Comment by Expander** [comment]
Or phrased in another way: My proposal was to extend the `fill(...)` function by another *optional* parameter, i.e. a parameter that can be given or omitted. However, I can't use references for this job, because the can't be optional (they don't have this desired semantics in C++). So, I propose to use a pointer, which can be `nullptr`, which means that no decays object is passed.

**Comment by pathron** [comment]
Yeah but the cost of having an optional parameter here is to use a pointer and use the `nullptr` when its omitted, which to me is less transparent and simple than just having an overload where a const ref is passed.  I don't mind if you really think this is better.

**Comment by Expander** [comment]
I would also be fine with an overload.

**Comment by wkotlarski** [comment]
In this approach this line
```
slha_io.fill(..., &decays);
```
has to be changed on meta level, or wrapped in `if` since decays might or might now exist.

**Comment by wkotlarski** [comment]
I think we actually need 2 separate versions of `fill` function. The reason being that if you disable decays in `FlexibleSUSY.m.in` then `MODEL_decays` doesn't exist and the code will not compile.

**Comment by Expander** [comment]
Sorry to troll you, but this is may be a case for using a pointer instead of a reference. :)
We can pass `nullptr` to indicate that no decays should be written to the SLHA output.

**Comment by wkotlarski** [comment]
It would have to be a pointer of type `void`, right?

**Comment by Expander** [comment]
Hmm, not sure, why do you think so? If one uses a pointer, a forward declaration of the pointed-to object is sufficient (same for reference).

**Comment by wkotlarski** [comment]
So I'd forward declared a class that might never exist, like
```
class @ModelName@_decays;
```
?

**Comment by Expander** [comment]
Yes. As long as you're not de-referencing the pointer and/or calling methods on it, this will compile just fine. It's an ordinary forward declaration.

**Comment by wkotlarski** [comment]
Could you see if you're ok with bd2c99cc8e4898b5a7a4a49e8edde4cf4008b0c7 changes.

**Comment by Expander** [comment]
~~~
models/MSSM/run_cmd_line_MSSM.cpp:143:16: error: type 'flexiblesusy::MSSM_decays' does not provide a call operator
      decays = decays(std::get<0>(models), qedqcd, input, HigherOrderSMCorrections::enable);
               ^~~~~~
~~~

**Comment by wkotlarski** [comment]
Sorry, I forgot add one change. Now it should be fine.
